services:
#  indexer:
#    image: listen-indexer
#    build:
#      context: ./listen-data
#      dockerfile: Dockerfile
#    env_file:
#      - ./listen-data/.env
#    volumes:
#      - ./listen-data/.env:/app/.env
#    environment:
#      - REDIS_URL=redis://default:123456@redis.listen.orb.local:6379
#      - CLICKHOUSE_URL=http://clickhouse.listen.orb.local:8123
#      - CLICKHOUSE_USER=click_admin
#      - CLICKHOUSE_PASSWORD=123456
#      - CLICKHOUSE_DATABASE=default
#    depends_on:
#      redis:
#        condition: service_healthy
#      clickhouse:
#        condition: service_healthy

#  adapter:
#    image: listen-adapter
#    build:
#      context: ./listen-adapter
#      dockerfile: Dockerfile
#    env_file:
#      - ./listen-adapter/.env
#    volumes:
#      - ./listen-adapter/.env:/app/.env
#    environment:
#      - REDIS_URL=redis://default:123456@redis.listen.orb.local:6379
#      - CLICKHOUSE_URL=http://clickhouse.listen.orb.local:8123
#      - CLICKHOUSE_USER=click_admin
#      - CLICKHOUSE_PASSWORD=123456
#      - CLICKHOUSE_DATABASE=default
#      - HOST=0.0.0.0
#      - PORT=6968
#    ports:
#      - 6968:6968
#    depends_on:
#      redis:
#        condition: service_healthy

  mysql:
    image: mysql:8.0
    container_name: mysql-server
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tradition
      MYSQL_USER: zms
      MYSQL_PASSWORD: 123456
    volumes:
      - /Volumes/wdata/data/mysql/data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    build:
      context: ./vendor/redis
      dockerfile: Dockerfile
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "1.5G"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    command: redis-server /usr/local/etc/redis/redis.conf --save "" --appendonly no
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    ports:
      - 8123:8123
      - 9000:9000
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      - CLICKHOUSE_PASSWORD=default
      - CLICKHOUSE_HOST=0.0.0.0
    volumes:
      - /Volumes/wdata/data/clickhouse/conf/config.xml:/etc/clickhouse-server/config.xml
      - /Volumes/wdata/data/clickhouse/conf/users.xml:/etc/clickhouse-server/users.xml
      - /Volumes/wdata/data/clickhouse/data:/var/lib/clickhouse
      - /Volumes/wdata/data/clickhouse/log:/var/log/clickhouse-server
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8123/ping",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
#
#  grafana:
#    image: grafana/grafana-oss
#    ports:
#      - 3001:3000
#    environment:
#      - GF_SECURITY_ADMIN_PASSWORD=admin
#
#  prometheus:
#    image: prom/prometheus
#    ports:
#      - 9090:9090
#    volumes:
#      - ./listen-engine/prometheus.yml:/etc/prometheus/prometheus.yml
#
  # this is not ran, would require tweaking the config
#  nginx:
#    image: nginx
#    ports:
#      - 6000:80
##      - 6001:443
#    volumes:
#      - ./vendor/nginx/nginx-online.conf:/etc/nginx/nginx-online.conf
##      - ./cert.pem:/etc/letsencrypt/live/api.listen-rs.com/fullchain.pem:ro
##      - ./privkey.pem:/etc/letsencrypt/live/api.listen-rs.com/privkey.pem:ro
#    network_mode: host

volumes:
  redis-data: