-- Your SQL goes here
CREATE TABLE `market_symbol` (
                                 `id` VARCHAR(250) NOT NULL PRIMARY KEY COMMENT '主键，建议为 symbol 或其派生标识',
                                 `exchange` VARCHAR(50) NOT NULL COMMENT '交易所名称，如 Binance、OKX',
                                 `symbol` VARCHAR(50) NOT NULL COMMENT '交易对，如 "ONEUSDT"',
                                 `pair` VARCHAR(50) NOT NULL COMMENT '交易对名称，通常与 symbol 一致',
                                 `contract_type` VARCHAR(30) NOT NULL COMMENT '合约类型，如 "PERPETUAL"',
                                 `delivery_date` BIGINT NOT NULL COMMENT '交割日期（毫秒时间戳）',
                                 `onboard_date` BIGINT NOT NULL COMMENT '上线日期（毫秒时间戳）',
                                 `status` VARCHAR(30) NOT NULL COMMENT '状态，如 "TRADING"',
                                 `maint_margin_percent` VARCHAR(50) NOT NULL COMMENT '维持保证金百分比',
                                 `required_margin_percent` VARCHAR(50) NOT NULL COMMENT '起始保证金百分比',
                                 `base_asset` VARCHAR(30) NOT NULL COMMENT '基础资产，如 "ONE"',
                                 `quote_asset` VARCHAR(30) NOT NULL COMMENT '报价资产，如 "USDT"',
                                 `margin_asset` VARCHAR(30) NOT NULL COMMENT '保证金资产',
                                 `price_precision` BIGINT UNSIGNED NOT NULL COMMENT '价格精度',
                                 `quantity_precision` BIGINT UNSIGNED NOT NULL COMMENT '数量精度',
                                 `base_asset_precision` BIGINT UNSIGNED NOT NULL COMMENT '基础资产精度',
                                 `quote_precision` BIGINT UNSIGNED NOT NULL COMMENT '报价资产精度',
                                 `underlying_type` VARCHAR(50) NOT NULL COMMENT '合约基础类型',
                                 `underlying_sub_type` JSON DEFAULT NULL COMMENT '合约子类型（JSON数组）',
                                 `trigger_protect` VARCHAR(50) NOT NULL COMMENT '触发保护百分比',
                                 `liquidation_fee` VARCHAR(50) NOT NULL COMMENT '清算手续费比例',
                                 `market_take_bound` VARCHAR(50) NOT NULL COMMENT '市价吃单最大偏移保护',
                                 `max_move_order_limit` BIGINT UNSIGNED NOT NULL COMMENT '最大移动下单限制',
                                 `filters` JSON DEFAULT NULL COMMENT '过滤器 JSON 列表',
                                 `order_types` JSON DEFAULT NULL COMMENT '支持的下单类型',
                                 `time_in_force` JSON DEFAULT NULL COMMENT '支持的 TIF 策略',
                                 `permission_sets` JSON DEFAULT NULL COMMENT '权限集',
                                 INDEX idx_symbol_exchange (exchange),
                                 UNIQUE KEY uq_exchange_symbol (exchange, symbol)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT ='交易对信息表';